sed -i 's/import { ABRAAO_SCENES, EPISODE_META_5, ABRAAO_QUIZ } from '\''\.\/data\/abraaoScript'\'';/import { ABRAAO_SCENES, EPISODE_META_5, ABRAAO_QUIZ } from '\''\.\/data\/abraaoScript'\'';\nimport { JOSE_SCENES, EPISODE_META_T2E1, JOSE_QUIZ } from '\''\.\/data\/joseScript'\'';/g' src/App.tsx

sed -i 's/const currentScenes = currentEpisodeId === '\''t1e5'\'' ? ABRAAO_SCENES : currentEpisodeId === '\''t1e4'\'' ? BABEL_SCENES : currentEpisodeId === '\''t1e3'\'' ? NOE_SCENES : currentEpisodeId === '\''t1e2'\'' ? ADAO_EVA_SCENES : CREATION_SCENES;/const currentScenes = currentEpisodeId === '\''t2e1'\'' ? JOSE_SCENES : currentEpisodeId === '\''t1e5'\'' ? ABRAAO_SCENES : currentEpisodeId === '\''t1e4'\'' ? BABEL_SCENES : currentEpisodeId === '\''t1e3'\'' ? NOE_SCENES : currentEpisodeId === '\''t1e2'\'' ? ADAO_EVA_SCENES : CREATION_SCENES;/g' src/App.tsx

sed -i 's/const currentMeta = currentEpisodeId === '\''t1e5'\'' ? EPISODE_META_5 : currentEpisodeId === '\''t1e4'\'' ? EPISODE_META_4 : currentEpisodeId === '\''t1e3'\'' ? EPISODE_META_3 : currentEpisodeId === '\''t1e2'\'' ? EPISODE_META_2 : EPISODE_META;/const currentMeta = currentEpisodeId === '\''t2e1'\'' ? EPISODE_META_T2E1 : currentEpisodeId === '\''t1e5'\'' ? EPISODE_META_5 : currentEpisodeId === '\''t1e4'\'' ? EPISODE_META_4 : currentEpisodeId === '\''t1e3'\'' ? EPISODE_META_3 : currentEpisodeId === '\''t1e2'\'' ? EPISODE_META_2 : EPISODE_META;/g' src/App.tsx

sed -i 's/const currentQuiz = currentEpisodeId === '\''t1e5'\'' ? ABRAAO_QUIZ : currentEpisodeId === '\''t1e4'\'' ? BABEL_QUIZ : currentEpisodeId === '\''t1e3'\'' ? NOE_QUIZ : currentEpisodeId === '\''t1e2'\'' ? ADAO_EVA_QUIZ : CREATION_QUIZ;/const currentQuiz = currentEpisodeId === '\''t2e1'\'' ? JOSE_QUIZ : currentEpisodeId === '\''t1e5'\'' ? ABRAAO_QUIZ : currentEpisodeId === '\''t1e4'\'' ? BABEL_QUIZ : currentEpisodeId === '\''t1e3'\'' ? NOE_QUIZ : currentEpisodeId === '\''t1e2'\'' ? ADAO_EVA_QUIZ : CREATION_QUIZ;/g' src/App.tsx

sed -i 's/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'') {/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'') {/g' src/App.tsx
