sed -i 's/import { OS_DISCIPULOS_SCENES, EPISODE_META_T3E4, OS_DISCIPULOS_QUIZ } from '\''\.\/data\/osDiscipulosScript'\'';/import { OS_DISCIPULOS_SCENES, EPISODE_META_T3E4, OS_DISCIPULOS_QUIZ } from '\''\.\/data\/osDiscipulosScript'\'';\nimport { OS_MILAGRES_SCENES, EPISODE_META_T3E5, OS_MILAGRES_QUIZ } from '\''\.\/data\/osMilagresScript'\'';/g' src/App.tsx

sed -i 's/const currentScenes = currentEpisodeId === '\''t3e4'\'' ? OS_DISCIPULOS_SCENES : /const currentScenes = currentEpisodeId === '\''t3e5'\'' ? OS_MILAGRES_SCENES : currentEpisodeId === '\''t3e4'\'' ? OS_DISCIPULOS_SCENES : /g' src/App.tsx

sed -i 's/const currentMeta = currentEpisodeId === '\''t3e4'\'' ? EPISODE_META_T3E4 : /const currentMeta = currentEpisodeId === '\''t3e5'\'' ? EPISODE_META_T3E5 : currentEpisodeId === '\''t3e4'\'' ? EPISODE_META_T3E4 : /g' src/App.tsx

sed -i 's/const currentQuiz = currentEpisodeId === '\''t3e4'\'' ? OS_DISCIPULOS_QUIZ : /const currentQuiz = currentEpisodeId === '\''t3e5'\'' ? OS_MILAGRES_QUIZ : currentEpisodeId === '\''t3e4'\'' ? OS_DISCIPULOS_QUIZ : /g' src/App.tsx

sed -i 's/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'') {/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'' || ep.id === '\''t3e5'\'') {/g' src/App.tsx
