sed -i 's/import { A_MULTIPLICACAO_SCENES, EPISODE_META_T3E8, A_MULTIPLICACAO_QUIZ } from '\''\.\/data\/aMultiplicacaoScript'\'';/import { A_MULTIPLICACAO_SCENES, EPISODE_META_T3E8, A_MULTIPLICACAO_QUIZ } from '\''\.\/data\/aMultiplicacaoScript'\'';\nimport { A_RESSURREICAO_SCENES, EPISODE_META_T3E9, A_RESSURREICAO_QUIZ } from '\''\.\/data\/aRessurreicaoScript'\'';/g' src/App.tsx

sed -i 's/const currentScenes = currentEpisodeId === '\''t3e8'\'' ? A_MULTIPLICACAO_SCENES : /const currentScenes = currentEpisodeId === '\''t3e9'\'' ? A_RESSURREICAO_SCENES : currentEpisodeId === '\''t3e8'\'' ? A_MULTIPLICACAO_SCENES : /g' src/App.tsx

sed -i 's/const currentMeta = currentEpisodeId === '\''t3e8'\'' ? EPISODE_META_T3E8 : /const currentMeta = currentEpisodeId === '\''t3e9'\'' ? EPISODE_META_T3E9 : currentEpisodeId === '\''t3e8'\'' ? EPISODE_META_T3E8 : /g' src/App.tsx

sed -i 's/const currentQuiz = currentEpisodeId === '\''t3e8'\'' ? A_MULTIPLICACAO_QUIZ : /const currentQuiz = currentEpisodeId === '\''t3e9'\'' ? A_RESSURREICAO_QUIZ : currentEpisodeId === '\''t3e8'\'' ? A_MULTIPLICACAO_QUIZ : /g' src/App.tsx

sed -i 's/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'' || ep.id === '\''t3e5'\'' || ep.id === '\''t3e6'\'' || ep.id === '\''t3e7'\'' || ep.id === '\''t3e8'\'') {/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'' || ep.id === '\''t3e5'\'' || ep.id === '\''t3e6'\'' || ep.id === '\''t3e7'\'' || ep.id === '\''t3e8'\'' || ep.id === '\''t3e9'\'') {/g' src/App.tsx
