sed -i 's/import { JESUS_BATISMO_SCENES, EPISODE_META_T3E3, JESUS_BATISMO_QUIZ } from '\''\.\/data\/jesusBatismoScript'\'';/import { JESUS_BATISMO_SCENES, EPISODE_META_T3E3, JESUS_BATISMO_QUIZ } from '\''\.\/data\/jesusBatismoScript'\'';\nimport { OS_DISCIPULOS_SCENES, EPISODE_META_T3E4, OS_DISCIPULOS_QUIZ } from '\''\.\/data\/osDiscipulosScript'\'';/g' src/App.tsx

sed -i 's/const currentScenes = currentEpisodeId === '\''t3e3'\'' ? JESUS_BATISMO_SCENES : /const currentScenes = currentEpisodeId === '\''t3e4'\'' ? OS_DISCIPULOS_SCENES : currentEpisodeId === '\''t3e3'\'' ? JESUS_BATISMO_SCENES : /g' src/App.tsx

sed -i 's/const currentMeta = currentEpisodeId === '\''t3e3'\'' ? EPISODE_META_T3E3 : /const currentMeta = currentEpisodeId === '\''t3e4'\'' ? EPISODE_META_T3E4 : currentEpisodeId === '\''t3e3'\'' ? EPISODE_META_T3E3 : /g' src/App.tsx

sed -i 's/const currentQuiz = currentEpisodeId === '\''t3e3'\'' ? JESUS_BATISMO_QUIZ : /const currentQuiz = currentEpisodeId === '\''t3e4'\'' ? OS_DISCIPULOS_QUIZ : currentEpisodeId === '\''t3e3'\'' ? JESUS_BATISMO_QUIZ : /g' src/App.tsx

sed -i 's/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'') {/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'') {/g' src/App.tsx
