sed -i 's/import { AS_PARABOLAS_SCENES, EPISODE_META_T3E6, AS_PARABOLAS_QUIZ } from '\''\.\/data\/asParabolasScript'\'';/import { AS_PARABOLAS_SCENES, EPISODE_META_T3E6, AS_PARABOLAS_QUIZ } from '\''\.\/data\/asParabolasScript'\'';\nimport { A_TEMPESTADE_NO_MAR_SCENES, EPISODE_META_T3E7, A_TEMPESTADE_NO_MAR_QUIZ } from '\''\.\/data\/aTempestadeNoMarScript'\'';/g' src/App.tsx

sed -i 's/const currentScenes = currentEpisodeId === '\''t3e6'\'' ? AS_PARABOLAS_SCENES : /const currentScenes = currentEpisodeId === '\''t3e7'\'' ? A_TEMPESTADE_NO_MAR_SCENES : currentEpisodeId === '\''t3e6'\'' ? AS_PARABOLAS_SCENES : /g' src/App.tsx

sed -i 's/const currentMeta = currentEpisodeId === '\''t3e6'\'' ? EPISODE_META_T3E6 : /const currentMeta = currentEpisodeId === '\''t3e7'\'' ? EPISODE_META_T3E7 : currentEpisodeId === '\''t3e6'\'' ? EPISODE_META_T3E6 : /g' src/App.tsx

sed -i 's/const currentQuiz = currentEpisodeId === '\''t3e6'\'' ? AS_PARABOLAS_QUIZ : /const currentQuiz = currentEpisodeId === '\''t3e7'\'' ? A_TEMPESTADE_NO_MAR_QUIZ : currentEpisodeId === '\''t3e6'\'' ? AS_PARABOLAS_QUIZ : /g' src/App.tsx

sed -i 's/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'' || ep.id === '\''t3e5'\'' || ep.id === '\''t3e6'\'') {/if (ep.id === '\''t1e1'\'' || ep.id === '\''t1e2'\'' || ep.id === '\''t1e3'\'' || ep.id === '\''t1e4'\'' || ep.id === '\''t1e5'\'' || ep.id === '\''t2e1'\'' || ep.id === '\''t2e2'\'' || ep.id === '\''t2e3'\'' || ep.id === '\''t2e4'\'' || ep.id === '\''t2e5'\'' || ep.id === '\''t3e1'\'' || ep.id === '\''t3e2'\'' || ep.id === '\''t3e3'\'' || ep.id === '\''t3e4'\'' || ep.id === '\''t3e5'\'' || ep.id === '\''t3e6'\'' || ep.id === '\''t3e7'\'') {/g' src/App.tsx
